# Generated by Django 5.0.3 on 2024-03-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('species', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
            ],
        ),
    ]
