# Generated by Django 5.0.3 on 2024-03-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0002_customer_alter_pet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cname',
            new_name='name',
        ),
    ]
