# Generated by Django 5.0.3 on 2024-04-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0003_rename_cname_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
