# Generated by Django 5.0.4 on 2024-04-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0006_adminmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('emailId', models.CharField(max_length=100)),
                ('ordernumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('phoneno', models.BigIntegerField()),
                ('totalbillamount', models.FloatField(default=0.0)),
            ],
        ),
    ]
